server:
  port: 8080

ztm:
  executorPoolCount: 10
  estimateServiceUrl: "https://ckan2.multimediagdansk.pl/delays"
  stopTableListUrl: "https://ckan.multimediagdansk.pl/dataset/c24aa637-3619-4dc2-a171-a23eec8f2172/resource/4c4025f0-01bf-41f7-a39f-d156d201b82b/download/stops.json"
  displayMessageListUrl: "https://ckan2.multimediagdansk.pl/displayMessages"

logging:
  level:
    org.springframework.web: ERROR
    com.books: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"