server:
  port: 8080

ztm:
  executorPoolCount: 10
  apiUrl: "https://ckan2.multimediagdansk.pl"
  stopTableListUrl: "https://ckan.multimediagdansk.pl/dataset/c24aa637-3619-4dc2-a171-a23eec8f2172/resource/4c4025f0-01bf-41f7-a39f-d156d201b82b/download/stops.json"

logging:
  level:
    org.springframework.web: ERROR
    com.opengdansk: INFO
  pattern:
    console: "%clr(%d{yy-MM-dd E HH:mm:ss.SSS}){blue} %clr(%-5p) %clr(${PID}){faint} %clr(---){faint} %clr([%8.15t]){cyan} %clr(%-40.40logger{0}){blue} %clr(:){red} %clr(%m){faint}%n"